# Generated by Django 3.0.4 on 2020-04-09 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams_app', '0002_auto_20200409_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_member',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='member',
        ),
        migrations.AddField(
            model_name='teammembers',
            name='member',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
