# Generated by Django 3.0.4 on 2020-04-09 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams_app', '0005_auto_20200409_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-id']},
        ),
    ]
