# Generated by Django 3.0.4 on 2020-04-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams_app', '0008_auto_20200410_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='document',
            field=models.FileField(default=True, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
