# Generated by Django 3.0.4 on 2020-04-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams_app', '0010_auto_20200410_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_picture',
            field=models.ImageField(blank=True, null=True, upload_to='team_profile'),
        ),
    ]
